services:
  - type: web
    name: documenter-mcp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /
    autoDeploy: true 